// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
           'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
           'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmDbbtaLoAzb55a30KG5X0I0SlN7RpDzA',
    appId: '1:686452990628:web:cea6b1946600e490a9bc31',
    messagingSenderId: '686452990628',
    projectId: 'massari-574ff',
    authDomain: 'massari-574ff.firebaseapp.com',
    storageBucket: 'massari-574ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpNdbXmGx0SvrskLn6xI9Z6B8SgEOBgoQ',
    appId: '1:686452990628:ios:041d29008a8ec139a9bc31',
    messagingSenderId: '686452990628',
    projectId: 'massari-574ff',
    storageBucket: 'massari-574ff.firebasestorage.app',
    iosClientId: '686452990628-tblkqh5lquus1g26fvisce7t0nh0ne54.apps.googleusercontent.com',
    iosBundleId: 'com.masari.masariApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpNdbXmGx0SvrskLn6xI9Z6B8SgEOBgoQ',
    appId: '1:686452990628:ios:041d29008a8ec139a9bc31',
    messagingSenderId: '686452990628',
    projectId: 'massari-574ff',
    storageBucket: 'massari-574ff.firebasestorage.app',
    iosClientId: '686452990628-tblkqh5lquus1g26fvisce7t0nh0ne54.apps.googleusercontent.com',
    iosBundleId: 'com.masari.masariApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmDbbtaLoAzb55a30KG5X0I0SlN7RpDzA',
    appId: '1:686452990628:web:0e8031fa0856061ca9bc31',
    messagingSenderId: '686452990628',
    projectId: 'massari-574ff',
    authDomain: 'massari-574ff.firebaseapp.com',
    storageBucket: 'massari-574ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFVWnGbHrYL9SGYisMNGZD7UjjyaRknrE',
    appId: '1:686452990628:android:1bfb4a9309f31b24a9bc31',
    messagingSenderId: '686452990628',
    projectId: 'massari-574ff',
    storageBucket: 'massari-574ff.firebasestorage.app',
  );

}